spring.datasource.url=jdbc:mysql://localhost:3306/myjoblog?useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-dll=true 
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
server.port=8787

jwt.secret="4B6250655368566D597133743677397A24432646294A404E635266556A586E32"